apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-myapp
  namespace: allfiles-staging
  labels:
    app: mygoapp
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mygoapp
      env: staging
  template:
    metadata:
      labels:
        app: mygoapp
        env: staging
    spec:
      containers:
      - name: mygoapp
        image: docker.io/sutthiphong2005/docker-gs-ping:green
        ports:
        - containerPort: 8080
